### ISSUE TITLE
Verifying on different dataset and packaging

### ISSUE THREAD

**Issue by skjerns** [SajadMo/SleepEEGNet#1]
First of all: Great work! Nice to see people working on it and publishing their code open source.

Secondly: I would like to encourage you to verify your results on different datasets.
So far the biggest problem in sleep research is not to find an algorithm that works well on sleep-edfx but one that works 'in the wild'. This can only be verified by running on different datasets as well.
(The Sleep-EDFx is a very old dataset and absolutely overused, creating a bias in itself in AI/Sleep-research.)

For some data set suggenstions see https://github.com/skjerns/AutoSleepScorer#appendix-sleep-datasets ,  some of them are easily available, for others you need to apply (but should not be difficult)

As a further step, if testing on other data sets reveals a good generalization, I encourage you to publish some pre-trained weights. This way those could be included in open-source sleep software such as [visbrain](https://github.com/EtienneCmb/visbrain)

**Comment by MousaviSajad** [comment]
Many thanks for your comments and suggestions. As you may see, I have evaluated the model on the Sleep-EDFx 2013 and the latest version of Sleep-EDFx (i.e., 2018). I will perform it for some of the suggested datasets.
