### ISSUE TITLE
ImportError: No module named layers.core

### ISSUE THREAD

**Issue by Irving-ren** [SajadMo/SleepEEGNet#10]
Hi, MousaviSajad. Thanks for your contribution of code.

Could I ask which version of TensorFlow was using on this project? I got the following error while running this script. 

python seq2seq_sleep_sleep-EDF.py --data_dir data_2013/eeg_fpz_cz --output_dir output_2013 --n_folds 20

The error info: 
 File "seq2seq_sleep_sleep-EDF.py", line 17, in <module>
        from tensorflow.python.layers.core import Dense
ImportError: No module named layers.core

Best wishes

**Comment by MousaviSajad** [comment]
Hi,

I think it was Tensorflow r1.14.

Regards,
Sajad

**Comment by Irving-ren** [comment]
Hello, 

Thanks for replying. It turns out that the reason is another envs' problem, which was solved now. I am closing the issue for now.

Best wishes
Irving
